apiVersion: v2
name: q2o
description: Quick2Odoo Online Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: "4.0.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled

